<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSessionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sessions', function (Blueprint $table) {
            $table->uuid('key')->comment('uuid generated by client');
            $table->string('secret')->nullable();
            $table->unsignedBigInteger('user_id')->index();
            $table->string('otp')->nullable();
            $table->string('ip_address');
            $table
                ->integer('platform')
                ->default(config('sk.platforms.web'))
                ->comment('0->web, 1->android/ios, 2->api');
            $table
                ->string('platform_signature')
                ->comment('Store all information about platform type');
            $table->dateTime('last_active_at')->nullable();
            $table->integer('onboarding')->default(1);
            $table->softDeletes();
            $table->timestamps();

            $table
                ->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sessions');
    }
}
